### PR TITLE
Scaling the video as it is drawn to the canvas.

### PR DESCRIPTION
**Pull request by vitch**
When you draw the video to the canvas you have to tell it the size of
the canvas so that it can scale the video appropriately and is
analysing the whole frame of the video when looking for QR codes.

My use-case is a responsive website where the canvas is the size of the 
available screen width. On narrow screens without this code you would
only see a crop of the video...

### CODE REVIEW

**Comment by cirocosta** [comment]
:+1: great @vitch .

For those wondering about these extra parameters to `drawImage`:  https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D#drawImage()

**Comment by vitch** [comment]
Although I've just noticed some problems with it... You have to know what aspect ratio your source camera is when you set the canvas size otherwise it messes up the capturing. A further pull request is on the way!

**Comment by cirocosta** [comment]
that's great! If you could describe the problem more precisely in the next pr i'd appreciate a bunch. I'm not very into this and would love to learn more :neckbeard:

**Comment by vitch** [comment]
Sure - I'll try to :smile: 

By the way, the demo html page has got errors at the moment - I'm not sure why. I was going to update it to illustrate something but couldn't figure out what the problem was...

**Comment by cirocosta** [comment]
Working well here. What errors are raising?

**Comment by vitch** [comment]
Two problems...
1. Until you give the camera permissions it says: `Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided.` - actually, I've fixed this I think in an unrelated commit locally.
2. It doesn't prompt for camera permissions when viewed over `file://`. I guess this is part of the browser's security model but I didn't know and because I was seeing the problem above I thought that was a fatal error.

So... Ignore me! And I'll submit another pull request in a bit and try and explain the problems I was running into and trying to solve!

**Comment by cirocosta** [comment]
The first one was definetly a problem but the second is actually something that i've forgotten to document. Thanks again!

**Pull request merged**
